### ISSUE TITLE
Recurring tasks feature

### ISSUE THREAD

**Issue by rizwaanimr** [mhss1/MyBrain#85]
**Is your feature request related to a problem?
 Data entered in the app get loss if you change or reset your device's and task doesn't has its repeated notification option for example if I set a task for wifi bill for October 1st I wish to have a reputation option of notification at November 1st for the same wifi bill every month 1st I need a reminder of my wifi bill.

**Describe the solution you'd like**
Create a internal backup and restore feature.
Add a feature call reputation of day, week and month feature in the task.

**Additional context**
This is a great app wish the developer to reach success in this and in his future projects as well.

**Comment by mhss1** [comment]
Thank you for your suggestion. I'll do my best to implement the features you mentioned 👍

**Comment by mateimm** [comment]
A month ago my phone got reset because I couldn't restart it. So, I have lost a great deal of notes saved on my phone on a similar app but not so nice as this one. 

What I would suggest is not only a manual import and export of data. With the manual export you never know when you get into a situation like I did and can not know when to make backups, unless you do them on a daily basis. And even then, if the backup is on the phone and the phone gets reset then you are at square one again. 

My suggestion is, beside the import and export of a manual backup, to also have a cloud based encrypted backup. So that the policy of this app still is valid as it would not require internet, unless the user decides to. And will not collect data as it will be saved encrypted anywhere the user chooses to (some options will be Dropbox, Onedrive, Gdrive). I guess that from the privacy point of view, as long as it is encrypted, no big data company can use it no matter where it is stored. 

This seems to be a beautiful project and I hope this can be implemented.

**Comment by mhss1** [comment]
Added recurring tasks in the latest update
