### ISSUE TITLE
Calendar shows events of one calendar twice

### ISSUE THREAD

**Issue by toshi2d** [mhss1/MyBrain#96]
**Describe the bug**
Calendar shows event twice from one of the calendars

**To Reproduce**
1. Open app and go to calendar
2. add event to one of the calendar

**Expected behavior**
Expected to see only one event

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - OS: Android 13
 - App Version: 1.0.3

**Comment by SteveMutter** [comment]
Can Confirm this Bug. 

Steps to reproduce the behavior:

   1. Open App and Open Calendar
   2. Add Test Event to one of three Calendars
   3. All Events in All Calendars doubled

Expected behavior
Expected to see only one event

Screenshots
![Screenshot_20221026-213607_My_Brain](https://user-images.githubusercontent.com/98714111/198120228-034859df-db20-4a22-8104-5fefa478a6f0.png)

Smartphone (please complete the following information):

    Device: VollaPhone
    OS: VollaOS based on Android 11
    App Version: 1.0.3

**Comment by mhss1** [comment]
Fixed
